# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3656550f15c5304cd743027398bfad827242c6945847bf9ee9251a6d6d39e0761af59f906191b79865580f03a8a6f1b02b22208f03b512acf0d3c284f377f2b

test:
  secret_key_base: b554129c4841d71b5d1b46d26470e64478e9da250ba70736d40148dfd5e6377cc601e51142bc5cf8cdbce59293fb6e4e592d26226530c1e9cbe6527037faa82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
